name: CI in Docker

on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '42 5 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.30'
          - '5.42'

    runs-on: ubuntu-latest
    name: OS Perl ${{matrix.perl-version}}
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
        # https://hub.docker.com/r/perldocker/perl-tester

    steps:
    - uses: actions/checkout@v6
    - name: Show Perl Version
      run: |
        perl -v

    - name: Install Dist::Zilla
      run: |
        cpanm -v
        cpanm --notest --verbose Dist::Zilla

    - name: Install Modules
      run: |
        dzil authordeps --missing | cpanm --notest --verbose
        dzil listdeps --develop --missing | cpanm --notest --verbose
        dzil listdeps --author --missing | cpanm --notest --verbose

    - name: Run tests
      env:
        AUTHOR_TESTING: 1
        RELEASE_TESTING: 1
      run: |
        dzil test --author --release

